version: '3.4'

services:
  identityservice:
    image: identityservice
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - identityservice_db
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python3 /tmp/debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
      ]
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=identity_db
      - POSTGRES_USER=identity_user
      - POSTGRES_PASSWORD=identity_password
      - POSTGRES_HOST=0.0.0.0

  identityservice_db:
    image: postgres:11.10-alpine
    container_name: identityservice_db
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=identity_db
      - POSTGRES_USER=identity_user
      - POSTGRES_PASSWORD=identity_password
      - POSTGRES_HOST=0.0.0.0
    ports:
      - 5432:5432
